// Generated by CoffeeScript 1.7.1
(function() {
  var Index, r;

  Index = (function() {
    function Index() {
      this.get();
    }

    Index.prototype.get = function() {
      var prm;
      return prm = $.getJSON('index.js').promise().done(function(index) {
        return r.set('index.data', index);
      });
    };

    return Index;

  })();

  r = new Ractive({
    el: '#content',
    template: '#template',
    data: {
      pageElement: 'finished',
      index: new Index,
      editing: false,
      showHelper: false
    }
  });

  r.on('edit', function(e) {
    return console.log(e);
  });

  Mousetrap.bind('/', function() {
    return r.set('pageElement', 'all');
  });

  Mousetrap.bind('.', function() {
    return r.set('pageElement', 'finished');
  });

  window.r = r;

}).call(this);

//# sourceMappingURL=app.map
