// Generated by CoffeeScript 1.7.1
(function() {
  var prm, r;

  r = new Ractive({
    el: '#content',
    template: '#template',
    data: {
      pageElement: 'finished',
      index: [],
      editing: false,
      showHelper: false
    }
  });

  r.on('edit', function(e) {
    return console.log(e);
  });

  prm = $.getJSON('index.js').promise();

  prm.done(function(index) {
    return r.set('index', index);
  });

  Mousetrap.bind('/', function() {
    return r.set('pageElement', 'all');
  });

  Mousetrap.bind('.', function() {
    return r.set('pageElement', 'finished');
  });

  window.r = r;

}).call(this);

//# sourceMappingURL=app.map
